[package]
name = "int"
version = "0.3.0"
authors = ["Sergey Shandar"]
description = "Integer traits"
license = "Apache-2.0"
repository = "https://github.com/rust-common/int"

[dependencies]
num-traits = "^0.2.6"
